version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app:delegated
      - /app/node_modules
#  tests:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - .:/app:cached
#      - /app/node_modules
#    command: ["yarn", "test"]